name: GcloudAuth
on: 
  workflow_dispatch:
  


jobs:
  Gcloud_auth:
    runs-on: ubuntu-latest
    steps:
    - uses: 'actions/checkout@v3'

    - id: 'auth'
      name: 'Authenticate to Google Cloud'
      uses: 'google-github-actions/auth@v1'
      with:
        token_format: 'access_token'
        credentials_json: '${{ secrets.GOOGLE_CREDENTIALS }}'
      
    - name: print auth token
      run: echo "${{ steps.auth.outputs.access_token}}"
